name: ESLINT + JEST ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      env: 
      with:
        node-version: '19'

    - name: Install dependencies
      run: make install

    - name: Install eslint locally
      run: npm install --save eslint-config-airbnb

    - name: Run eslint
      run: make lint

    - name: Run testing
      run: make jest
